---
quiet: true
skip-check:
- CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
- CKV_DOCKER_3 # Ensure that a user for the container has been created
- CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty.
- CKV_K8S_14 # Image Tag should be fixed - not latest or blank
- CKV_K8S_15 # Image Pull Policy should be Always
- CKV_K8S_21 # The default namespace should not be used
- CKV_K8S_38 # Ensure that Service Account Tokens are only mounted where necessary
- CKV_K8S_43 # Image should use digest
- CKV2_GHA_1 # Ensure top-level permissions are not set to write-all
- CKV2_K8S_6 # Minimize the admission of pods which lack an associated NetworkPolicy
