apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ coalesce .Values.DEPLOYMENT_RESOURCE_NAME .Values.SERVICE_NAME }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: open-telemetry-collector
    app.kubernetes.io/managed-by: saasDeployer
spec:
  scaleTargetRef:
    {{- if eq .Values.PAAS_PLATFORM "KUBERNETES" }}
    apiVersion: apps/v1
    kind: Deployment
    {{- else if eq .Values.PAAS_PLATFORM "OPENSHIFT" }}
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    {{- end }}
    name: '{{ coalesce .Values.DEPLOYMENT_RESOURCE_NAME .Values.SERVICE_NAME }}'
{{- if .Values.HPA_ENABLED }}
  minReplicas: {{ coalesce .Values.HPA_MIN_REPLICAS .Values.REPLICAS }}
  maxReplicas: {{ .Values.HPA_MAX_REPLICAS }}
{{- else }}
  minReplicas: 1
  maxReplicas: 9999
{{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ int (divf (mulf (default 75 .Values.HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT) (include "to_millicores" .Values.resources.limits.cpu)) (include "to_millicores" .Values.resources.requests.cpu)) }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ default 0 .Values.HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_UP_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_UP_PERCENT_VALUE (ge (int .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_UP_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_UP_PODS_VALUE (ge (int .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS) 0) }}
        - type: Pods
          value: {{ .Values.HPA_SCALING_UP_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS }}
{{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ default 300 .Values.HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_DOWN_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_DOWN_PERCENT_VALUE (ge (int .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_DOWN_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_DOWN_PODS_VALUE (ge (int .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS) 0)}}
        - type: Pods
          value: {{ .Values.HPA_SCALING_DOWN_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS }}
{{- end }}
