{{- if .Values.OTEC_SENTRY_ENVELOPES_INGRESS_ENABLED }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/component: open-telemetry-collector
    app.kubernetes.io/part-of: observability
  {{- if .Values.OTEC_SENTRY_ENVELOPES_INGRESS_ANNOTATIONS }}
  annotations:
    {{- toYaml (.Values.OTEC_SENTRY_ENVELOPES_INGRESS_ANNOTATIONS) | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.SERVICE_NAME}}-{{ .Values.NAMESPACE}}.{{ .Values.CLOUD_PUBLIC_HOST}}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: '{{ .Values.SERVICE_NAME }}'
                port:
                  name: sentry-receiver
{{- end }}