dist:
  name: qubership-open-telemetry-collector
  description: Custom OTel Collector for qubership platform
  #version: 0.122.1
  output_path: ./
exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter latest
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter latest
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter latest
  - gomod:    
      github.com/Netcracker/qubership-open-telemetry-collector/exporter/logtcpexporter add-tailbased-tracing
      
      
processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor latest

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver latest
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver latest
  - gomod:
      github.com/Netcracker/qubership-open-telemetry-collector/receiver/sentryreceiver add-tailbased-tracing


providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider latest
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider latest

extensions:
    - gomod:
        github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension latest
    - gomod:
        github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension latest
        
connectors:
    - gomod:
        github.com/Netcracker/qubership-open-telemetry-collector/connector/sentrymetricsconnector add-tailbased-tracing
    - gomod:
        github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector latest

replaces:
  - github.com/Netcracker/qubership-open-telemetry-collector/exporter/logtcpexporter => ./exporter/logtcpexporter
  - github.com/Netcracker/qubership-open-telemetry-collector/receiver/sentryreceiver => ./receiver/sentryreceiver
  - github.com/Netcracker/qubership-open-telemetry-collector/connector/sentrymetricsconnector => ./connector/sentrymetricsconnector