name: Build-test-qubership-open-telemetry-collector

on:
  workflow_run:
    workflows: ["Build Artifacts"]
    types:
      - completed
  workflow_dispatch:
  pull_request:
    branches:
      - all

env:
  kind_name: kind-cluster
  kind_version: v0.27.0
  collector_namespace: monitoring
  max_attempts: 30
  delay: 10

jobs:
  Run-build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code otel-collecor
        uses: actions/checkout@v4
        with:
         path: qubership-open-telemetry-collector
         
      - name: Set up Kind
        run: |
          curl -sLo ./kind https://kind.sigs.k8s.io/dl/${{ env.kind_version }}/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/
          kind delete cluster --name ${{ env.kind_name }}
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          name:  ${{ env.kind_name }}
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          EOF
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Build and load qubership-open-telemetry-collector
        run: |
                docker build ./qubership-open-telemetry-collector/ -t qubership-open-telemetry-collector
                kind --name ${{ env.kind_name }} load docker-image docker.io/library/qubership-open-telemetry-collector:latest

      - name: Install qubership-open-telemetry-collector
        run: |
              helm upgrade --install -n ${{ env.collector_namespace }} --create-namespace qubership-open-telemetry-collector ./qubership-open-telemetry-collector/charts/open-telemetry-collector/ \
              --set JAEGER_COLLECTOR_HOST=jaeger-collector.${{ env.jaeger_namespace }}.svc.cluster.local \
              --set JAEGER_COLLECTOR_OTLP_PORT:=4317
              kubectl wait --for=condition=Ready pod --all -n ${{ env.collector_namespace }} --timeout=60s

      - name: Cleanup
        run: |
              kind delete cluster --name ${{ env.kind_name }}
    