name: Scout repository scan
on:
  workflow_dispatch: {}
  schedule:
  # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
permissions:
  contents: read
jobs:
  scout_repo_scan:
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Analyze for critical and high CVEs
      id: docker-scout-cves
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
      continue-on-error: true
      with:
        command: cves
        image: fs://../${{ github.event.repository.name }}
        sarif-file: sarif.output.json
        summary: true
        ignore-base: true
        dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
        dockerhub-password: ${{ secrets.DOCKERHUB_RW_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload SARIF result
      uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
      with:
        sarif_file: sarif.output.json
